### PR TITLE
Basic tagging

### PR DESCRIPTION
**Pull request by JesperDramsch**
First tagging capabilitites for uploads. Editable after first upload. Shown in Box for picking and results.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Great start — thank you! Definitely want tags in there, going to be important soon. 

These UI widgets look pretty cool. Maybe you want to take a look and see if one of these might work for the front end? 

- My favourite: http://timschlechter.github.io/bootstrap-tagsinput/examples/
- Another: http://welldonethings.com/tags/manager/v3

Unfortunately I think it'd need a typeahead library too, eg http://twitter.github.io/typeahead.js/

It would also be nice to have a rudimentary way to filter on the tags in the gallery view. 

(Either way, I will look at this again tomorrow after check the last PR, which came in right before this one.)

**Comment by JesperDramsch** [comment]
It love to work on this. It be very happy if you just assign the issue to
me for now and I'll hack away on it.
Am 19.02.2015 04:42 schrieb "Matt Hall" <notifications@github.com>:

**Comment by JesperDramsch** [comment]
There's something funky in the Bootstrap 3 Typeahead. I can't figure it out, but somehow the item gets dropped upon selection. This is something, someone more knowledgeable should probably have a look at. It works, but it throws a js-error.

I'd be happy about any help I can get.

**Comment by kwinkunks** [comment]
Hey Jesper, I will try to check it out tonight... Thanks for giving it a
go!!  /m

**Comment by kwinkunks** [comment]
Looking at the data model, I think it may be better to use a list of db.Category instead of StringList...

    tags = db.ListProperty(db.Category, default=[])

And rather than allowing *any* tag, I think I'd like to have only admins (later, users with privileges) add new tags. So I think we need validation... see what it says here about validation of listed properties: https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses#ListProperty

Thanks again for continuing this Jesper... going to be awesome. 

Wondering if we should put this in a feature branch... not sure if I can do that with this PR myself or if you have to do it...

**Comment by JesperDramsch** [comment]
There is some client side restriction. But server side needs to be added.

Which tags would be good?

**Pull request closed without merging**
